import { useEffect, useState } from "react";
import { api } from "../services/api";

const initialForm = { projectId: "", title: "", useCase: "GENERAL_ASSISTANCE", prompt: "", dataClassification: "INTERNAL", containsPersonalData: false };
const labels = {
  GENERAL_ASSISTANCE: "General assistance", SURVEY_SUMMARY: "Survey summary", DATA_QUALITY: "Data quality review",
  RISK_REVIEW: "Risk review", DOCUMENT_EXTRACTION: "Document extraction"
};
const formatDate = value => value ? new Date(value).toLocaleString() : "-";

export default function AIRecords({ currentUser }) {
  const [config, setConfig] = useState(null);
  const [projects, setProjects] = useState([]);
  const [rows, setRows] = useState([]);
  const [form, setForm] = useState(initialForm);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [reviewNotes, setReviewNotes] = useState({});

  const load = async () => {
    const [status, projectRows, inferenceRows] = await Promise.all([api("/ai/status"), api("/projects"), api("/ai/inferences")]);
    setConfig(status); setProjects(projectRows); setRows(inferenceRows);
  };
  useEffect(() => { load().catch(e => setError(e.message)); }, []);

  const submit = async event => {
    event.preventDefault(); setBusy(true); setError(""); setNotice("");
    try {
      const created = await api("/ai/inferences", { method: "POST", body: JSON.stringify({ ...form, projectId: form.projectId || null }) });
      setForm(initialForm);
      setNotice(`AI output generated by ${created.modelName} and queued for human review.`);
    } catch (e) { setError(e.message); }
    finally { await load().catch(e => setError(e.message)); setBusy(false); }
  };

  const review = async (id, decision) => {
    setBusy(true); setError(""); setNotice("");
    try {
      await api(`/ai/inferences/${id}/review`, { method: "PATCH", body: JSON.stringify({ decision, note: reviewNotes[id] || "" }) });
      setNotice(`Output ${decision.toLowerCase()} successfully.`); await load();
    } catch (e) { setError(e.message); }
    finally { setBusy(false); }
  };
  const canReview = ["ADMIN", "MANAGER"].includes(currentUser?.role);

  return <section className="ai-console">
    <div className="page-head">
      <div><span className="eyebrow">Governed intelligence</span><h2>AI Governance & Inference</h2></div>
      <span className={`provider-state ${config?.configured ? "ready" : "offline"}`}>{config?.configured ? `${config.provider} ready` : "Provider setup required"}</span>
    </div>
    {!config?.configured && <div className="ai-setup"><strong>AI provider is not configured.</strong><span>Add <code>OPENAI_API_KEY</code> to the server environment, then restart the API. The key is never sent to the browser.</span></div>}
    {error && <p className="error">{error}</p>}{notice && <p className="success">{notice}</p>}

    <div className="ai-summary">
      <div><span>Provider</span><strong>{config?.provider || "OpenAI"}</strong></div><div><span>Model</span><strong>{config?.model || "-"}</strong></div>
      <div><span>Awaiting review</span><strong>{rows.filter(row => row.status === "PENDING_REVIEW").length}</strong></div><div><span>Released</span><strong>{rows.filter(row => row.status === "APPROVED").length}</strong></div>
    </div>

    <form className="ai-request" onSubmit={submit}>
      <div className="ai-request-head"><div><span className="eyebrow">New request</span><h3>Run governed AI</h3></div><small>External calls are blocked for restricted or personal data.</small></div>
      <label>Title<input required minLength="3" maxLength="255" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} placeholder="e.g. Review survey field notes"/></label>
      <label>Project<select value={form.projectId} onChange={e => setForm({ ...form, projectId: e.target.value })}><option value="">No project</option>{projects.map(project => <option key={project.id} value={project.id}>{project.code} - {project.name}</option>)}</select></label>
      <label>Use case<select value={form.useCase} onChange={e => setForm({ ...form, useCase: e.target.value })}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
      <label>Data classification<select value={form.dataClassification} onChange={e => setForm({ ...form, dataClassification: e.target.value })}>{["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"].map(value => <option key={value}>{value}</option>)}</select></label>
      <label className="ai-prompt">Prompt / business task<textarea required minLength="10" maxLength={config?.maxPromptChars || 12000} rows="7" value={form.prompt} onChange={e => setForm({ ...form, prompt: e.target.value })} placeholder="Provide the task and only the minimum necessary, de-identified context..."/><small>{form.prompt.length}/{config?.maxPromptChars || 12000} characters</small></label>
      <label className="check ai-sensitive"><input type="checkbox" checked={form.containsPersonalData} onChange={e => setForm({ ...form, containsPersonalData: e.target.checked })}/>This prompt contains personal data</label>
      <div className="ai-submit"><button disabled={busy || !config?.configured}>{busy ? "Processing..." : "Run AI & queue review"}</button></div>
    </form>

    <div className="ai-history-head"><div><span className="eyebrow">Evidence trail</span><h3>Inference history</h3></div><span className="count">{rows.length} runs</span></div>
    <div className="ai-runs">{rows.length ? rows.map(row => <article className="ai-run" key={row.id}>
      <div className="ai-run-top"><div><span className={`ai-status status-${row.status.toLowerCase()}`}>{row.status.replaceAll("_", " ")}</span><h4>{row.title}</h4></div><span className="muted">{formatDate(row.createdAt)}</span></div>
      <div className="ai-meta"><span>{labels[row.useCase]}</span><span>{row.dataClassification}</span><span>{row.modelName || row.providerName}</span>{row.Project && <span>{row.Project.code}</span>}{row.totalTokens != null && <span>{row.totalTokens} tokens</span>}{row.latencyMs != null && <span>{(row.latencyMs / 1000).toFixed(1)}s</span>}</div>
      <details><summary>Input and lineage</summary><p className="ai-text">{row.prompt}</p><code className="hash">SHA-256: {row.promptHash}</code></details>
      {row.responseText && <div className="ai-output"><strong>AI draft</strong><p className="ai-text">{row.responseText}</p></div>}
      {row.failureReason && <p className="ai-failure">{row.failureReason}</p>}{row.reviewNote && <p className="ai-review-note"><strong>Review note:</strong> {row.reviewNote}</p>}
      <div className="ai-run-foot"><span>Requested by {row.requestedBy?.name || "Unknown"}</span>{row.reviewedBy && <span>Reviewed by {row.reviewedBy.name} · {formatDate(row.reviewedAt)}</span>}</div>
      {row.status === "PENDING_REVIEW" && canReview && <div className="ai-review"><input value={reviewNotes[row.id] || ""} onChange={e => setReviewNotes({ ...reviewNotes, [row.id]: e.target.value })} placeholder="Review note (recommended)"/><button type="button" disabled={busy} onClick={() => review(row.id, "APPROVED")}>Approve & release</button><button type="button" disabled={busy} className="reject" onClick={() => review(row.id, "REJECTED")}>Reject</button></div>}
    </article>) : <div className="empty ai-empty">No AI runs yet. Submit the first governed request above.</div>}</div>
  </section>;
}
