import { useEffect, useMemo, useState } from "react";
import { api } from "../services/api";
import "../marketing.css";

const initial = { title: "", clientName: "", contactPerson: "", enquiryNumber: "", source: "OTHER", sourceLink: "", scope: "", location: "", service: "", estimatedValue: "", submissionDeadline: "", emdAmount: "", tenderFee: "", eligibilityCriteria: "", assignedExecutiveId: "" };
const money = value => Number(value || 0).toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const label = value => String(value || "-").replaceAll("_", " ");
const sources = ["GEM", "CPPP", "EPROCURE", "PRIVATE_ENQUIRY", "EXISTING_CLIENT", "EMAIL", "WEBSITE", "LINKEDIN", "PARTNER", "OTHER"];

export default function Marketing({ currentUser }) {
  const [summary, setSummary] = useState({}); const [rows, setRows] = useState([]); const [team, setTeam] = useState([]);
  const [form, setForm] = useState(initial); const [selectedId, setSelectedId] = useState(null); const [query, setQuery] = useState("");
  const [notes, setNotes] = useState(""); const [screening, setScreening] = useState("BID_RECOMMENDED"); const [managerDecision, setManagerDecision] = useState("RECOMMEND_GO"); const [adminDecision, setAdminDecision] = useState("GO_FOR_BID");
  const [cost, setCost] = useState({ category: "MANPOWER", description: "", quantity: 1, rate: "" }); const [activity, setActivity] = useState({ activityType: "FOLLOW_UP", details: "", nextFollowUpAt: "" });
  const [submission, setSubmission] = useState({ portalName: "", bidReference: "", quotedValue: "", submissionReceipt: "" }); const [result, setResult] = useState({ status: "TECHNICAL_EVALUATION", reason: "" });
  const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const canManage = ["ADMIN", "MANAGER", "MARKETING_MANAGER"].includes(currentUser.role);
  const load = async (search = query) => { try { const suffix = search ? `?q=${encodeURIComponent(search)}` : ""; const [stats, opportunities, members] = await Promise.all([api("/marketing/dashboard"), api(`/marketing/opportunities${suffix}`), api("/marketing/team")]); setSummary(stats); setRows(opportunities); setTeam(members); } catch (e) { setError(e.message); } };
  useEffect(() => { load(""); }, [currentUser.id]);
  const selected = useMemo(() => rows.find(row => row.id === selectedId), [rows, selectedId]);
  const run = async (path, options, success) => { setError(""); setMessage(""); try { await api(path, options); setNotes(""); setMessage(success); await load(); } catch (e) { setError(e.message); } };
  const field = (key, value) => setForm(current => ({ ...current, [key]: value }));

  return <section className="marketing-page">
    <div className="page-head"><div><span className="eyebrow">Lead to project</span><h2>Marketing</h2></div><span className="count">{summary.active || 0} active</span></div>
    <p className="muted">Search opportunities, bid through Executive → Manager → Admin approval, follow up, and convert awards into projects.</p>
    {error && <p className="error">{error}</p>}{message && <p className="success">{message}</p>}
    <div className="cards marketing-stats">{[["Active pipeline", summary.active], ["Pipeline value", money(summary.pipelineValue)], ["Manager pending", summary.managerPending], ["Admin pending", summary.adminPending], ["Bid preparation", summary.bidsInPreparation], ["Submitted", summary.submitted], ["Awarded", summary.awarded], ["Win rate", `${summary.winPercentage || 0}%`], ["Deadlines (7 days)", summary.upcomingDeadlines], ["Overdue follow-ups", summary.overdueFollowUps]].map(([name, value]) => <div className="card" key={name}><strong className="small">{value ?? 0}</strong><span>{name}</span></div>)}</div>

    <details className="marketing-panel"><summary>Add opportunity / tender</summary><form className="form-grid" onSubmit={async e => { e.preventDefault(); await run("/marketing/opportunities", { method: "POST", body: JSON.stringify(form) }, "Opportunity registered"); setForm(initial); }}>
      <label>Work title<input required value={form.title} onChange={e => field("title", e.target.value)}/></label><label>Client<input required value={form.clientName} onChange={e => field("clientName", e.target.value)}/></label>
      <label>Contact person<input value={form.contactPerson} onChange={e => field("contactPerson", e.target.value)}/></label><label>Tender / enquiry no.<input value={form.enquiryNumber} onChange={e => field("enquiryNumber", e.target.value)}/></label>
      <label>Source<select value={form.source} onChange={e => field("source", e.target.value)}>{sources.map(x => <option key={x}>{x}</option>)}</select></label><label>Source link<input type="url" value={form.sourceLink} onChange={e => field("sourceLink", e.target.value)}/></label>
      <label>Service<input value={form.service} onChange={e => field("service", e.target.value)}/></label><label>Location<input value={form.location} onChange={e => field("location", e.target.value)}/></label>
      <label>Estimated value<input type="number" min="0" value={form.estimatedValue} onChange={e => field("estimatedValue", e.target.value)}/></label><label>Deadline<input type="datetime-local" value={form.submissionDeadline} onChange={e => field("submissionDeadline", e.target.value)}/></label>
      <label>EMD<input type="number" min="0" value={form.emdAmount} onChange={e => field("emdAmount", e.target.value)}/></label><label>Tender fee<input type="number" min="0" value={form.tenderFee} onChange={e => field("tenderFee", e.target.value)}/></label>
      {canManage && <label>Marketing executive<select value={form.assignedExecutiveId} onChange={e => field("assignedExecutiveId", e.target.value)}><option value="">Unassigned</option>{team.filter(x => x.role === "MARKETING_EXECUTIVE").map(x => <option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}
      <label>Scope<textarea value={form.scope} onChange={e => field("scope", e.target.value)}/></label><label>Eligibility criteria<textarea value={form.eligibilityCriteria} onChange={e => field("eligibilityCriteria", e.target.value)}/></label><div className="actions"><button>Register opportunity</button></div>
    </form></details>

    <div className="pipeline-toolbar"><input placeholder="Search client, tender, location or service" value={query} onChange={e => setQuery(e.target.value)}/><button onClick={() => load()}>Search</button><button className="secondary" onClick={() => { setQuery(""); load(""); }}>Clear</button></div>
    <div className="marketing-layout"><div className="table-wrap"><table><thead><tr><th>Opportunity</th><th>Client</th><th>Deadline</th><th>Value</th><th>Owner</th><th>Status</th></tr></thead><tbody>{rows.length ? rows.map(row => <tr className={selectedId === row.id ? "selected-row" : ""} key={row.id} onClick={() => setSelectedId(row.id)}><td>{row.title}<small className="block">{row.enquiryNumber || row.source}</small></td><td>{row.clientName}</td><td>{row.submissionDeadline ? new Date(row.submissionDeadline).toLocaleString() : "-"}</td><td>{money(row.estimatedValue)}</td><td>{row.assignedExecutive?.name || "Unassigned"}</td><td><span className="status">{label(row.status)}</span></td></tr>) : <tr><td className="empty" colSpan="6">No matching opportunity.</td></tr>}</tbody></table></div>

      <aside className="opportunity-detail">{selected ? <><span className="eyebrow">Selected opportunity</span><h3>{selected.title}</h3><p>{selected.scope || "No scope entered"}</p><p className="muted">{selected.clientName} · {selected.location || "Location pending"}</p><div className="detail-grid"><span>Status <b>{label(selected.status)}</b></span><span>EMD <b>{money(selected.emdAmount)}</b></span><span>Quoted <b>{money(selected.quotedValue)}</b></span><span>Follow-up <b>{selected.nextFollowUpAt ? new Date(selected.nextFollowUpAt).toLocaleString() : "-"}</b></span></div>
        {["NEW", "SCREENING"].includes(selected.status) && ["ADMIN", "MARKETING_EXECUTIVE", "MARKETING_MANAGER"].includes(currentUser.role) && <Workflow title="Executive screening" options={["BID_RECOMMENDED", "NO_BID_RECOMMENDED", "MORE_INFORMATION_REQUIRED", "HOLD"]} value={screening} setValue={setScreening} notes={notes} setNotes={setNotes} button="Send to manager" onClick={() => run(`/marketing/opportunities/${selected.id}/screen`, { method: "PATCH", body: JSON.stringify({ recommendation: screening, notes }) }, "Sent to Marketing Manager")}/>} 
        {selected.status === "MANAGER_REVIEW" && canManage && <Workflow title="Marketing Manager review" options={["RECOMMEND_GO", "RECOMMEND_NO_BID", "RETURN_TO_EXECUTIVE", "HOLD"]} value={managerDecision} setValue={setManagerDecision} notes={notes} setNotes={setNotes} button="Submit review" onClick={() => run(`/marketing/opportunities/${selected.id}/manager-review`, { method: "PATCH", body: JSON.stringify({ decision: managerDecision, notes }) }, "Manager decision recorded")}/>} 
        {selected.status === "ADMIN_REVIEW" && currentUser.role === "ADMIN" && <Workflow title="Admin Go / No-Go" options={["GO_FOR_BID", "NO_BID", "HOLD", "APPROVE_WITH_CONDITIONS", "RETURN_TO_MANAGER"]} value={adminDecision} setValue={setAdminDecision} notes={notes} setNotes={setNotes} button="Confirm decision" onClick={() => run(`/marketing/opportunities/${selected.id}/admin-decision`, { method: "PATCH", body: JSON.stringify({ decision: adminDecision, notes }) }, "Admin decision recorded")}/>} 
        {["BID_APPROVED", "BID_PREPARATION"].includes(selected.status) && canManage && <form className="workflow-box" onSubmit={async e => { e.preventDefault(); await run(`/marketing/opportunities/${selected.id}/cost-items`, { method: "POST", body: JSON.stringify(cost) }, "Cost item added"); setCost({ category: "MANPOWER", description: "", quantity: 1, rate: "" }); }}><h4>BOQ & costing</h4><select value={cost.category} onChange={e => setCost({ ...cost, category: e.target.value })}>{["MANPOWER", "EQUIPMENT", "TRAVEL", "SOFTWARE", "VENDOR", "EMD_BG", "OVERHEAD", "CONTINGENCY", "PROFIT", "TAX", "OTHER"].map(x => <option key={x}>{x}</option>)}</select><input required placeholder="Description" value={cost.description} onChange={e => setCost({ ...cost, description: e.target.value })}/><div className="split"><input required type="number" min="0.01" step="0.01" value={cost.quantity} onChange={e => setCost({ ...cost, quantity: e.target.value })}/><input required type="number" min="0" step="0.01" placeholder="Rate" value={cost.rate} onChange={e => setCost({ ...cost, rate: e.target.value })}/></div><button>Add cost</button>{selected.costItems?.map(item => <small key={item.id}>{item.category}: {item.description} — {money(item.amount)}</small>)}<b>Total: {money(selected.costItems?.reduce((sum, item) => sum + Number(item.amount), 0))}</b></form>}
        {["BID_APPROVED", "BID_PREPARATION"].includes(selected.status) && canManage && <div className="workflow-box"><h4>Submit approved bid</h4>{Object.keys(submission).map(key => <input key={key} type={key === "quotedValue" ? "number" : "text"} placeholder={label(key)} value={submission[key]} onChange={e => setSubmission({ ...submission, [key]: e.target.value })}/>)}<button onClick={() => run(`/marketing/opportunities/${selected.id}/submit`, { method: "PATCH", body: JSON.stringify(submission) }, "Bid submitted and locked")}>Record submission</button></div>}
        {selected.submittedAt && !["AWARDED", "LOST", "NO_BID"].includes(selected.status) && canManage && <Workflow title="Post-bid status" options={["TECHNICAL_EVALUATION", "QUALIFIED", "FINANCIAL_EVALUATION", "NEGOTIATION", "AWARDED", "LOST"]} value={result.status} setValue={value => setResult({ ...result, status: value })} notes={result.reason} setNotes={value => setResult({ ...result, reason: value })} button="Update result" onClick={() => run(`/marketing/opportunities/${selected.id}/result`, { method: "PATCH", body: JSON.stringify(result) }, "Bid status updated")}/>} 
        {selected.status === "AWARDED" && currentUser.role === "ADMIN" && !selected.convertedProjectId && <div className="workflow-box"><h4>Award conversion</h4><p>Client, scope, location and approved value will transfer to a planned project.</p><button onClick={() => run(`/marketing/opportunities/${selected.id}/convert-project`, { method: "POST", body: "{}" }, "Award converted to project")}>Convert to project</button></div>}{selected.convertedProjectId && <p className="success">Converted to project</p>}
        <form className="workflow-box" onSubmit={async e => { e.preventDefault(); await run(`/marketing/opportunities/${selected.id}/activities`, { method: "POST", body: JSON.stringify(activity) }, "Activity recorded"); setActivity({ activityType: "FOLLOW_UP", details: "", nextFollowUpAt: "" }); }}><h4>CRM activity / follow-up</h4><select value={activity.activityType} onChange={e => setActivity({ ...activity, activityType: e.target.value })}>{["CALL", "EMAIL", "MEETING", "FOLLOW_UP", "CLARIFICATION", "PRESENTATION", "NEGOTIATION", "NOTE"].map(x => <option key={x}>{x}</option>)}</select><textarea required placeholder="Activity details" value={activity.details} onChange={e => setActivity({ ...activity, details: e.target.value })}/><label>Next follow-up<input type="datetime-local" value={activity.nextFollowUpAt} onChange={e => setActivity({ ...activity, nextFollowUpAt: e.target.value })}/></label><button>Add activity</button>{selected.activities?.slice().reverse().map(item => <p key={item.id}><b>{label(item.activityType)}</b> · {new Date(item.occurredAt).toLocaleString()}<br/><small>{item.details}</small></p>)}</form>
      </> : <p className="muted">Select an opportunity to review its workflow, costing, submission and follow-ups.</p>}</aside>
    </div>
  </section>;
}

function Workflow({ title, options, value, setValue, notes, setNotes, button, onClick }) {
  return <div className="workflow-box"><h4>{title}</h4><select value={value} onChange={e => setValue(e.target.value)}>{options.map(x => <option key={x}>{x}</option>)}</select><textarea placeholder="Assessment / decision notes" value={notes} onChange={e => setNotes(e.target.value)}/><button onClick={onClick}>{button}</button></div>;
}
